name: Build and deploy Node.js app to Azure Web App - Programmeren4Avans

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Mocha
        run: npm install -g mocha

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          mocha -reporter spec share-a-meal/test/**/*.test.js --exit
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50B8FBB8D97C410B8A4FE3919360429C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A1BAD5C28B1443C807471A9E3BF254A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61FB8905DECD4E39B9FC31B80E2480F2 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Programmeren4Avans'
          slot-name: 'Production'
          package: .